name: Quantum
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.13.5
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pywin32=311
  - pyzmq=27.0.1
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - contourpy==1.3.3
      - cryptography==45.0.5
      - cycler==0.12.1
      - dill==0.4.0
      - fonttools==4.59.0
      - h5py==3.14.0
      - ibm-cloud-sdk-core==3.24.2
      - ibm-platform-services==0.68.1
      - idna==3.10
      - kiwisolver==1.4.8
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - numpy==2.3.2
      - pandas==2.3.2
      - pbr==6.1.1
      - pillow==11.3.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyparsing==3.2.3
      - pyspnego==0.11.2
      - pytz==2025.2
      - qiskit==1.4.3
      - qiskit-aer==0.17.1
      - qiskit-algorithms==0.3.1
      - qiskit-ibm-runtime==0.40.1
      - qiskit-nature==0.7.2
      - requests==2.32.4
      - requests-ntlm==1.3.0
      - rustworkx==0.16.0
      - scipy==1.16.1
      - sspilib==0.3.1
      - stevedore==5.4.1
      - symengine==0.13.0
      - sympy==1.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0